---
- hosts: all
  become: yes
  tasks:
   - name: Download a WAR File to the Tomcat webapps directory to be deployed
     maven_artifact:
       group_id: com.devops4solutions
       artifact_id: LoginWebApp
       extension: war
       repository_url: 'http://"${nexus_ip}":8081/repository/maven-releases/'
       version: "{{ ArtifactVersion }}"
       vars_files : config.yml
       dest: /opt/apache-tomcat-9.0.65/webapps/
