---
- hosts: all
  become: true
  tasks:
   - name: Add the User Tomcat
     user:
       name: tomcat
       shell: /sbin/nologin
   - name: Download Tomcat
     get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.68/bin/apache-tomcat-9.0.68.tar.gz
      dest: /usr/local/
   - name: 5) Install the Tomcat
     unarchive:
      src: /usr/local/apache-tomcat-9.0.68.tar.gz
      dest: /usr/local/
      remote_src: yes
   - name: 6) Changing the Tomcat File Ownership, Group and Permissions
     file:
      path: /usr/local/apache-tomcat-9.0.68
      owner: tomcat
      group: tomcat
      recurse: yes
      state: directory
   - name: start tomcat services
     shell: nohup /usr/local/apache-tomcat-9.0.68/bin/startup.sh
   
         
...